config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'server/index'
  # Defines the root path route ("/")
  # root "articles#index"
  # resources:server
  root to:"server#index"
  resources :users
  
   get 'new' => "books/new"
   get 'books/index'
   resources :books
    get 'books/show'
   
  resources :books, only: [:index,:new,:show,:create] do
    collection do
      get 'search'
      post 'search'
    end
  end

    resources :reservations do
    collection do
    post 'confirm'
    end
  end
    


    # get 'books/new'
  # resources :users, only: [:show]
  # devise_for :users, controllers: {
  #   registrations: 'users/registrations'
  # }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

  require 'pry'
 
  belongs_to :user
  has_many :reservations
  mount_uploader:room_image,RoomImageUploader
  has_one_attached :room_image
  
  validates :room_name, presence: true
  validates :room_introduce, presence: true
  validates :fee, presence: true
  validates :addres, presence: true
  validates :room_image, presence: true
  validate :minfee
  def minfee
    errors.add(:fee, "は1円以上にしてください") if fee < 0 
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :people, presence: true
  validate :errors_matter
  def errors_matter
    errors.add(:start_date, "は終了日以前の日付にしてください") if start_date > end_date
    errors.add(:start_date, "は本日以降の日付にしてください") if start_date.strftime('%Y-%m-%d') < Date.current.strftime('%Y-%m-%d')
    errors.add(:people, "は一人以上にしてください") if people < 1 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books
  has_many :reservations, dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
  
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :avatar])
    end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
   def index
    # binding.pry
    @user = current_user
    @books = Book.all
    # binding.pry
   end

  def new
    @user = current_user
    @book = Book.new
  end


  def create
    @user = current_user
    @book = Book.new(params.require(:book).permit(:room_name, :room_introduce, :fee, :addres, :room_image ))
    # binding.pry
    if @book.save
      # binding.pry
      redirect_to :books, notice: "保存しました。"
    else
      # binding.pry
      flash[:alert] = "問題が発生しました。"
      render :new, status: :unprocessable_entity
    end
  end


  def show
    @books = Book.find(params[:id])
  end
  

  def update
    new_params = book_params
    if @book.update(new_params)
      flash[:notice] = "保存しました。"
    else
      flash[:alert] = "問題が発生しました。"
    end
    redirect_back(fallback_location: request.referer)
  end

  def search
     @user = current_user
     @books = Book.where('books.addres LIKE(?)',"%#{params[:addres]}%")
     @numbers = @books.count
   if params[:keyword].present?
     @books = Book.where([ 'books.addres LIKE ? OR books.room_introduce LIKE ? OR books.room_name LIKE ? ', "%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%" ])
     @numbers = @books.count
   end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    @user = User.new(user_params)
  end
  
  def update
    if @user.update_without_password(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def update_resource(resource, params)
    resource.update_without_current_password(params) 
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :avatar )
    end
    
  def after_update_path_for(resource)
    user_path(@user.id)
  end 
  
  def after_sign_in_path_for(resource)
    blogs_path
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

require "pry"

  def index
    @user = current_user
    @reservations = Reservation.all
  end

  def new
    @user = current_user
    @book = Book.find(params[:id])
    @reservation = Reservation.new
  end

  def confirm
    @user = current_user
    @reservation = Reservation.new(reservation_params)
    
    if @reservation.invalid?
       @book = @reservation.book
       render "new", status: :unprocessable_entity
    else
      @book = @reservation.book
      @reservation.total_day = (@reservation.end_date - @reservation.start_date)/86400.to_i
      @reservation.total_price = (@book.fee * @reservation.total_day * @reservation.people).to_i
    end
    
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:book_id,:user_id,:start_date,:end_date,:price,:total_price,:people,:total_day))
    # binding.pry
    if params[:back] || !@reservation.save
       render "index", status: :unprocessable_entity
    #binding.pry
    else
       redirect_to  reservations_path(@reservation), notice: "予約が完了しました"
    #binding.pry
    end
  end

  def show
    @user = current_user
    @reservation = Reservation.find(params[:id])
    @books = @reservation.book_id
  end 

  private

  def reservation_params
    params.permit(:book_id,:user_id,:start_date,:end_date,:people)
  end
end

app/controllers/server_controller.rb
class ServerController < ApplicationController
  def index  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/server_helper.rb
module ServerHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/index.html.erb
<div class="container-fiuld reservations">
    <h4 class="pb-4">登録済みルーム一覧</h4>
    <table>
        <thead>
            <tr align="center">
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>作成日</th>
            </tr>
        </thead>
        <tbody>
            <% @books.each do |book| %>
                <tr>
                    <td>
                    <%= image_tag book.room_image.url, :size => '240x140' %> 
                    </td>
                    <td class="posts-name"><%= link_to "#{book.room_name}", {controller: 'books', action: 'show', id: book.id} %> </td>
                    <td class="posts-content"><%= book.room_introduce %></td>
                    <td class="price-icon"><%= book.fee%></td>   
                    <td><%= book.created_at.strftime('%Y-%m-%d')  %></td>   
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/books/new.html.erb
<section class="section">
　　<div class="container">
        <article class="panel">
            <div class="panel-heading">
                ルーム情報登録
            </div>
            <%= render "shared/error", obj: @book %>
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <%= form_for @book do |f| %>
                            <div class="col-md-4 select">
                                <div class="form-group">
                                <%= f.label :ルーム名 %><br />
                                <%= f.text_field :room_name, autofocus: true %>
                                </div>
                            </div>
                            
                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <%= f.label :ルーム紹介 %><br />
                                    <%= f.text_area :room_introduce, autofocus: true %>
                                </div>
                            </div>
                            <br/>
                            <br/>
                            <br/>
                            <div class="col-md-3 select">
                                <div class="form-group">
                                    <%= f.label :料金 %><br />
                                    <%= f.number_field :fee, autofocus: true %>
                                </div>
                            </div>    
                           
                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <%= f.label :住所 %><br />
                                    <%= f.text_field :addres, autofocus: true %>
                                </div>
                            </div>
                            <br/>
                            <br/>
                            <br/>
                            <div class="col-md-4 select">
                                <div class="form-group">
                                     <%= f.label :ルーム画像 %><br />
                                     <%= f.file_field :room_image %>
                                </div>
                            </div>
                            <br/>
                            <br/>
                            <br/>
                            <br/>
                            <div><%= f.submit "登録", class: "button is-primary" %></div>
                        <% end %>
                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

app/views/books/search.html.erb
<div class="container-fluid room">
  <h4><%= "検索結果：#{@numbers}件" %></h4>
  <div class="row room-row">
    <div class="room-information">
      <% @books.each do |book| %>
        <div class="room-frame-inner">
            <%= link_to controller: 'books', action: 'show', id: book.id do %>
                <div class="room-image-out">
                  <%= image_tag book.room_image.url, :alt => 'ルーム画像', class: "frame-room-image" %>
                  <div class="room-profile">
                    <p class="room-profile-name">
                      <%= book.room_name %>
                    </p>
                    <p class="room-profile-city">
                      <%= book.addres %>
                    </p>
                    <p class="room-profile-price">
                      ¥<%= book.fee %>
                    </p>
                  </div>
                </div>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
  
</div>

app/views/books/show.html.erb
<div class = "show-all">
  <div class = "book-show">
    <h3>ルーム詳細</h3>
     <table>
       <tr>
        <td><%= image_tag @books.room_image.url,:size => '400x280'%></td>
       </tr>
      <tr>
     </table>
  </div>
 
  <div class = "book-detail">
    <table>
       <th>ルーム名</th>
       <td><%= @books.room_name %></td>
     </tr>
     <tr>
       <th>ルーム紹介</th>
       <td><%= @books.room_introduce %></td>
     </tr>
     <tr>
       <th>料金/日</th>
       <td><%= @books.fee %></td>
     </tr>
     <tr>
       <th>住所</th>
       <td><%= @books.addres %></td>
     </tr>
   </table>
     <%= link_to "予約する", {controller: 'reservations', action: 'new', id: @books.id},{class: "book-room"} %>
 </div>

</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Server</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <header>
        <a href="/server/index"><img src = "https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" class = "logo"></a>
           <%= form_with url: search_books_path, data: {turbo: false} do |f| %>
              <div class = "search_form">
                <%= f.text_field :addres, class: "header-input", placeholder: "エリア" %>
                <i class="fa-solid fa-location-dot"></i>
                <%= f.text_field :keyword, class: "header-input", placeholder: "キーワード" %>
                <%= f.submit :search, class: "hidden-btn" %>
           <% end %>      
              </div>
      
      <div class = "logcontainer">
          <% if user_signed_in? %>
          <p class = "user-name"><%= current_user.name %></p>
          <div class="dropdown">
            <button type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar.url, :size => '70x45' %>
              <% else %>
              画像なし
              <% end %>
           </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><%= link_to "ルーム登録", new_book_path, class:"dropdown-item" %></li>
              <li><%= link_to "登録済みルーム一覧", books_path, class:"dropdown-item" %></li>
              <li><%= link_to "予約済みルーム一覧", reservations_path, class:"dropdown-item" %></li>
              <li><%= link_to "プロフィール変更", edit_user_registration_path, class:"dropdown-item" %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
            </ul>
          </div>
      </div>
          <% else %>
            <%= link_to new_user_registration_path do %>
              <button class="btn btn-primary mr-2">新規登録</button>
            <% end %>
            <%= link_to new_user_session_path do %>
              <button class="btn btn-success ml-2">ログイン</button>
            <% end %>
　　　    <% end %>  
    </header>
    
        <div class="notice-message">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
    </div>

    <div class="alert-message">
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
  </div>
    <%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <footer>
    <p>© 2020 POTEPAN.INC.</p>　
  </footer>
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="container reservations-new">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="reservations-new-nav">
                <h4 class="reservations-new-check-content">予約内容確認</h4>
                        
                        <div class="reservations-new-date-selsct">

                            <%= form_with model:@reservation, url: {controller: 'reservations', action: 'create' }, data: {turbo: false} do |f| %>
                            <%= f.hidden_field :people %>
                            <%= f.hidden_field :book_id %>
                            <%= f.hidden_field :user_id %>

                            <%= f.label :start_date ,"開始日" %>
                            <%= f.hidden_field :start_date %>
                            <%= f.text_field :start_date, class:"form-control col-md-9 mb-8",:readonly => true %>
                            <br><%= f.label :end_date ,"終了日" %>
                            <%= f.hidden_field :end_date %>
                            <%= f.text_field :end_date, class:"form-control col-md-9 mb-8",:readonly => true %>


                            <h6 class="reservations-new-check-content">使用日数 : <%= @reservation.total_day %>日</h6>
                            <%= f.hidden_field :total_day  %>

                            <h6 class="reservations-new-check-content">人数 : <%= @reservation.people %>人</h6>

                            <%= f.label :total_price ,"合計金額" %><br>
                            <%= f.hidden_field :total_price %>
                            <%= f.text_field :total_price, class:"form-control col-md-9 mb-8",:readonly => true %>

                            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
                            
                            
                        
                            <%= f.submit "予約を確定" ,class:"col-md-2 btn btn-primary my-3 form-control form-btn"%>
                            <%= link_to "ルーム詳細に戻る",:back ,class:"btn btn-secondary form-control"%>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/reservations/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/reservations/index.html.erb
<div class="container-field reservations">
  <h4>予約済みルーム一覧</h4>
  <table class="reservations">
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= image_tag reservation.book.room_image.url, :size => '240x140' %></td>
          <td class="posts-name"><%= link_to "#{reservation.book.room_name}", {controller: 'reservations', action: 'new', id: reservation.book.id} %> </td>
          <td class="posts-contents"><%= reservation.book.room_introduce %></td>
          <td>¥ <%= reservation.total_price %></td>
          <td><%= reservation.start_date.strftime('%Y-%m-%d') %></td>
          <td><%= reservation.end_date.strftime('%Y-%m-%d') %></td>
          <td><%= reservation.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<div class="container room-show">
    <div class="row">
        <div class="col-md-8">
            <%= render "shared/error", obj: @reservation %>
            <image src=" <%= @book.room_image %> " onerror= "this.src='https://presite-potepancamp-rails-02.herokuapp.com/assets/room01.jpg';" class="room-show-image">
            <div class="room-show-detile">
                <div class="room-show-profile">
                    <p class="room-show-profile-name">
                        部屋名　<%= @book.room_name %>
                    </p>
                    <p class="room-show-profile-address">
                        住所　<%= @book.addres %>
                    </p>
                </div>
            </div>
            <p class="room-show-detile-content">
            部屋紹介　<%= @book.room_introduce %>
            </p>
            <p class="room-show-profile-address">
            料金　<%= @book.fee %>円/１日
            </p>
        </div>

        <div class="col-md-4">
            <div class="room-show-nav">
                <%= form_with url: confirm_reservations_path, data: {turbo: false} do |f| %>
                <%= f.hidden_field :book_id, :value => @book.id %>
                <%= f.hidden_field :user_id, :value => @user.id %>
                
                    <div class="room-show-date-select">
                        <%= f.label :book_id ,"部屋ID"%>
                        <%= @book.id%>　<br><br>
                        
                        <%= f.label :start_date ,"開始日"%>
                        <%= f.date_field :start_date ,class:"form-control mb-7" %>
                        <%= f.label :end_date ,"終了日"%>
                        <%= f.date_field :end_date ,class:"form-control mb-7" %>
                        <%= f.label :people ,"人数"%>
                        <%= f.number_field :people ,class:"form-control mb-7" %>
                        <%= f.submit "予約する",class:"form-control btn btn-primary"%>
                    </div>
                <% end %>
            </div>
        </div>    
    </div>
</div>

app/views/reservations/show.html.erb
<h3>ルーム詳細</h3>
 
 <table>
   <tr>
    <td><%= image_tag @books.room_image.url %></td>
   </tr>
   <tr>
     <th>ルーム名</th>
     <td><%= @books.room_name %></td>
   </tr>
   <tr>
     <th>ルーム紹介</th>
     <td><%= @books.room_introduce %></td>
   </tr>
   <tr>
     <th>料金/日</th>
     <td><%= @books.fee %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= @books.addres %></td>
   </tr>

</table>

app/views/server/index.html.erb
<div class = "mainbody">
  <div class = "topmain">
    <div class = "sercharea">
      <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_cover_top.jpg" alt = "山の景色">
         <section class = "serch-design">
           <p class="form-area-title mb-4">Potepan Shareでまだ体験したことない旅をしよう</p>
           <p class="form-area-title mb-5">
             <%= form_with url: {controller: 'books', action: 'search' }, data: {turbo: false} do |f| %>
             <%= f.text_field :addres, class: "body-input", placeholder: "東京" %>
             <%= submit_tag '検索' , class:"btn-primary mb-6"%>
             <% end %>
           </section>
         </div>
    </div>
  </div>
</div>
          
     
      <div class = "container">
        <h1 class = "smalltitle">おすすめのエリア</h1>
          <div class = "pointview">
            <img class = "tokyo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg" alt="東京スカイツリー" width="240" height="360">
            <img class = "oosaka" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg" alt="大阪城" width="240" height="360">
　　　　    <img class = "kyoto" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg" alt="京都タワー" width="240" height="360">
　　　　    <img class = "sapporo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg" alt="札幌時計台" width="240" height="360">
          </div>
      </div>
  

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
   <% obj.errors.full_messages.each do |message| %>
     <ul>
       <li><%= message %></li>
     </ul>
   <% end %>
<% end %>